# Generated by Django 5.1.6 on 2025-03-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowing',
            options={'ordering': ['-expected_return_date']},
        ),
    ]
