# Generated by Django 5.1.6 on 2025-03-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0004_alter_borrowing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowing',
            options={'ordering': ['actual_return_date', 'expected_return_date']},
        ),
    ]
