# Generated by Django 5.1.6 on 2025-03-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0005_alter_borrowing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrow_date',
            field=models.DateField(),
        ),
    ]
