# Generated by Django 5.1.6 on 2025-03-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0007_alter_borrowing_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrow_date',
            field=models.DateField(),
        ),
    ]
