# Generated by Django 5.1.6 on 2025-03-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0009_alter_borrowing_options_alter_borrowing_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
