# Generated by Django 5.1.6 on 2025-03-04 09:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0010_alter_borrowing_borrow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='borrow_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
