# Generated by Django 5.1.6 on 2025-03-04 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_url', models.URLField(max_length=500)),
                ('session_id', models.CharField(max_length=255)),
                ('amount_of_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Paid'), (-1, 'Expired')], default=0)),
                ('type', models.IntegerField(choices=[(1, 'PAYMENT'), (-1, 'FINE')])),
                ('borrowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='borrowing.borrowing')),
            ],
        ),
    ]
