# Generated by Django 5.1.6 on 2025-03-04 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0011_borrowing_created_at_alter_borrowing_borrow_date'),
        ('payment', '0002_alter_payment_session_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='borrowing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='borrowing.borrowing'),
        ),
    ]
